module.exports = {
  RABBITMQ_CONNECTION: 'RABBITMQ_CONNECTION_ERROR',
  FIELDS_REQUIRED: 'FIELDS_REQUIRED',
  KIND_AND_CHANNELNAME_REQUIRED: 'KIND_AND_CHANNELNAME_REQUIRED',
  KIND_OF_QUEUE_NOT_SUPPORTED: 'KIND_OF_QUEUE_NOT_SUPPORTED',
  EXCHANGE_NAME_REQUIRED: 'EXCHANGE_NAME_REQUIRED',
};
